Repository RVC-Project/Retrieval-based-Voice-Conversion-WebUI, pull requests merged in 2023-05, with the labels that each got.

#218 big_npy should be shuffled
  infer-web.py
Labels: enhancement

#219 [maintenance] cleanup one click training and related
  config.py
  infer-web.py
Labels: enhancement, good first issue

#259 remove Unnecessary elif
  vc_infer_pipeline.py
Labels: question

#298 fix: cannot merge model when model has f0 information in some language UI
  infer-web.py
  train/process_ckpt.py
Labels: documentation, enhancement

#357 add project name to index file's name
  infer-web.py
Labels: enhancement
