Repository RVC-Project/Retrieval-based-Voice-Conversion-WebUI, pull requests merged in 2023-09, with the labels that each got.

#1204 Feature: Intel ARC GPU support with IPEX
  configs/config.py
  docs/en/README.en.md
  docs/tr/README.tr.md
  infer/lib/infer_pack/models.py
  infer/lib/rmvpe.py
  infer/modules/ipex/__init__.py
  infer/modules/ipex/attention.py
  infer/modules/ipex/gradscaler.py
  infer/modules/ipex/hijacks.py
  infer/modules/train/train.py
  infer/modules/uvr5/modules.py
  infer/modules/vc/pipeline.py
  requirements-ipex.txt
Labels: documentation, enhancement, good first issue

#1257 Update README.md
  README.md
Labels: documentation

#1259 Optimize latency
  assets/Synthesizer_inputs.pth
  assets/hubert_inputs.pth
  assets/rmvpe_inputs.pth
  configs/config.json
  configs/config.py
  gui_v1.py
  infer/lib/infer_pack/models.py
  infer/lib/jit/__init__.py
  infer/lib/jit/get_hubert.py
  infer/lib/jit/get_rmvpe.py
  infer/lib/jit/get_synthesizer.py
  infer/lib/rmvpe.py
  tools/rvc_for_realtime.py
Labels: enhancement
