Repository RVC-Project/Retrieval-based-Voice-Conversion-WebUI, pull requests merged in 2023-04, with the labels that each got.

#35 add localization(添加本地化)
  extract_locale.py
  gui.py
  infer-web.py
  language/gitkeep
  language/language_gui.py
  locale/en_US.json
  locale/ja_JP.json
  locale/locale_diff.py
  locale/zh_CN.json
  webui_locale.py
Labels: documentation, enhancement, good first issue

#38 Fix GUI i18n
  gui.py
  locale/zh_CN.json
  requirements-win-for-realtime_vc_gui.txt
Labels: bug, documentation, enhancement

#39 fix: i18n导致无法启动 & 增加 --noautoopen 参数
  .github/workflows/genlocale.yml
  .github/workflows/unitest.yml
  config.py
  extract_locale.py
  gui.py
  infer-web.py
  locale/en_US.json
  locale/ja_JP.json
  locale/locale_diff.py
  locale/zh_CN.json
  webui_locale.py
Labels: bug, documentation, enhancement

#44 revert changes at #42
  .github/workflows/genlocale.yml
Labels: bug, documentation, invalid

#48 优化笔记本、翻译并重新引入自动push
  .github/workflows/genlocale.yml
  Retrieval_based_Voice_Conversion_WebUI.ipynb
  gui.py
  locale/en_US.json
  locale/ja_JP.json
  locale/zh_CN.json
Labels: bug, documentation, enhancement

#52 润色README及其日文翻译
  README.ja.md
  README.md
Labels: documentation, enhancement

#51 optimize: append pause to bat
  go-web.bat
Labels: enhancement

#55 add Discord badge to ZH_CN
  README.md
Labels: documentation

#56 add Discord badge to English&Japanese README
  README.en.md
  README.ja.md
Labels: documentation

#57 Reformat and rewrite _get_name_params
  config.py
  export_onnx.py
  extract_f0_print.py
  extract_feature_print.py
  extract_locale.py
  gui.py
  infer-web.py
  infer/infer-pm-index256.py
  infer/train-index.py
  infer/trans_weights.py
  infer_pack/commons.py
  infer_pack/models.py
  infer_pack/models_onnx.py
  infer_pack/transforms.py
  infer_uvr5.py
  locale/locale_diff.py
  my_utils.py
  slicer2.py
  train/data_utils.py
  train/losses.py
  train/mel_processing.py
  train/process_ckpt.py
  train/utils.py
  train_nsf_sim_cache_sid_load_pretrain.py
  trainset_preprocess_pipeline_print.py
  uvr5_pack/lib_v5/dataset.py
  uvr5_pack/lib_v5/layers.py
  uvr5_pack/lib_v5/layers_123812KB .py
  uvr5_pack/lib_v5/layers_123821KB.py
  uvr5_pack/lib_v5/layers_33966KB.py
  uvr5_pack/lib_v5/layers_537227KB.py
  uvr5_pack/lib_v5/layers_537238KB.py
  uvr5_pack/lib_v5/model_param_init.py
  uvr5_pack/lib_v5/nets.py
  uvr5_pack/lib_v5/nets_123812KB.py
  uvr5_pack/lib_v5/nets_123821KB.py
  uvr5_pack/lib_v5/nets_33966KB.py
  uvr5_pack/lib_v5/nets_537227KB.py
  uvr5_pack/lib_v5/nets_537238KB.py
  uvr5_pack/lib_v5/nets_61968KB.py
  uvr5_pack/lib_v5/spec_utils.py
  uvr5_pack/name_params.json
  uvr5_pack/utils.py
  vc_infer_pipeline.py
  webui_locale.py
Labels: enhancement, good first issue

#63 fix: extract locale regex
  extract_locale.py
Labels: bug

#60 新增 zh-TW 台灣正體中文語言包
  locale/locale_diff.py
  locale/zh_TW.json
Labels: documentation, enhancement, good first issue

#64 feat: link zh_TW.json to zh_HK.json & zh_SG.json
  locale/locale_diff.py
  locale/zh_HK.json
  locale/zh_SG.json
  webui_locale.py
Labels: documentation, enhancement

#62 workflow: add auto format job with black on pull request
  .github/workflows/black_PR.yml
Labels: documentation, enhancement

#66 optimize: 优化代码结构
  .github/workflows/genlocale.yml
  README.md
  docs/README.en.md
  docs/README.ja.md
  docs/小白简易教程.doc
  extract_locale.py
  gui.py
  i18n.py
  i18n/en_US.json
  i18n/ja_JP.json
  i18n/locale_diff.py
  i18n/zh_CN.json
  i18n/zh_HK.json
  i18n/zh_SG.json
  i18n/zh_TW.json
  infer-web.py
  locale/zh_HK.json
  locale/zh_SG.json
Labels: documentation, enhancement

#74 fix #73: 伴奏人声分离时报错：FileNotFoundError
  i18n/locale_diff.py
  uvr5_pack/utils.py
Labels: bug

#77 fix: i18n rename 不全
  i18n.py
Labels: bug

#79 Autoformat when pushed directly
  .github/workflows/push_format.yml
Labels: enhancement

#84 fix: json format
  extract_locale.py
  gui.py
  i18n/locale_diff.py
  infer-web.py
  trainset_preprocess_pipeline_print.py
  vc_infer_pipeline.py
Labels: bug

#92 Automatically change faiss version
  requirements.txt
Labels: bug, documentation, enhancement

#101 improved Japanese translation.
  docs/README.ja.md
Labels: documentation, enhancement

#94 some change precision audio processing
  extract_f0_print.py
  my_utils.py
  train/data_utils.py
  trainset_preprocess_pipeline_print.py
Labels: enhancement, good first issue

#108 Refactor GPU cache during training
  train_nsf_sim_cache_sid_load_pretrain.py
Labels: enhancement, good first issue

#194 added some more zh to en_US translation
  i18n/en_US.json
  i18n/es_ES.json
  i18n/ja_JP.json
  i18n/zh_CN.json
  i18n/zh_HK.json
  i18n/zh_SG.json
  i18n/zh_TW.json
  infer-web.py
Labels: documentation, enhancement

#208 update training tips and faiss tips
  docs/faiss_tips_en.md
  docs/faiss_tips_ja.md
  docs/training_tips_en.md
  docs/training_tips_ja.md
Labels: documentation, enhancement
