Repository RVC-Project/Retrieval-based-Voice-Conversion-WebUI, pull requests merged in 2024-04, with the labels that each got.

#1946 docs: Update README.ja.md
  docs/jp/README.ja.md
Labels: documentation

#1942 Fix typo in readme
  README.md
Labels: documentation

#1928 Move to Gradio 4.23.0
  Retrieval_based_Voice_Conversion_WebUI.ipynb
  Retrieval_based_Voice_Conversion_WebUI_v2.ipynb
  infer-web.py
  requirements-amd.txt
  requirements-dml.txt
  requirements-ipex.txt
  requirements-py311.txt
  requirements.txt
Labels: enhancement, dependencies

#1921 Fix i18n
  infer-web.py
Labels: documentation

#1872 Specify numpy version at requirement.txt
  requirements.txt
Labels: bug, dependencies

#1937 optimize(dockerfile): 将"copy . ."移至系统设置之后
  Dockerfile
Labels: enhancement

#1940 fix: update python version limit
  README.md
Labels: documentation

#1984 kill child process after closing the gui
  gui_v1.py
Labels: bug

#1991 fix: ValueError: mode must be 'r', 'w', or None, got: wb
  infer/lib/audio.py
Labels: bug

#1994 fix: fix realtime gui launch script for windows
  go-realtime-gui.bat
Labels: bug

#1999 New feature of real-time voice changing: formant shift adjustment
  configs/config.json
  gui_v1.py
  i18n/locale/en_US.json
  i18n/locale/es_ES.json
  i18n/locale/fr_FR.json
  i18n/locale/it_IT.json
  i18n/locale/ja_JP.json
  i18n/locale/ko_KR.json
  i18n/locale/pt_BR.json
  i18n/locale/ru_RU.json
  i18n/locale/tr_TR.json
  i18n/locale/zh_CN.json
  i18n/locale/zh_HK.json
  i18n/locale/zh_SG.json
  i18n/locale/zh_TW.json
  infer/lib/infer_pack/models.py
  infer/lib/rtrvc.py
Labels: enhancement

#2003 修复了Onnx Attention的一个Shape错误
  infer/lib/infer_pack/attentions_onnx.py
  infer/lib/infer_pack/models_onnx.py
  infer/modules/onnx/export.py
  tools/onnx/export_onnx.py
Labels: bug

#1934 feat: add fcpe to pipeline
  infer/modules/vc/pipeline.py
Labels: enhancement

#2011 fix(RVCMD): is_win issue
  infer/lib/rvcmd.py
Labels: bug
