Repository RVC-Project/Retrieval-based-Voice-Conversion-WebUI, pull requests merged in 2024-01, with the labels that each got.

#1683 add is_half argument to extract_feature_print.py
  .github/workflows/unitest.yml
  Retrieval_based_Voice_Conversion_WebUI.ipynb
  Retrieval_based_Voice_Conversion_WebUI_v2.ipynb
  infer-web.py
  infer/modules/train/extract_feature_print.py
Labels: bug

#1712 Docs: Update README.fr.md
  README.md
  docs/en/README.en.md
  docs/fr/README.fr.md
  docs/jp/README.ja.md
  docs/kr/README.ko.han.md
  docs/kr/README.ko.md
  docs/tr/README.tr.md
Labels: documentation

#1715 fix poetry part for README.md
  README.md
  poetry.lock
  pyproject.toml
Labels: dependencies

#1693 optimize: realtime inference
  configs/config.json
  gui_v1.py
  i18n/locale/en_US.json
  i18n/locale/es_ES.json
  i18n/locale/fr_FR.json
  i18n/locale/it_IT.json
  i18n/locale/ja_JP.json
  i18n/locale/ru_RU.json
  i18n/locale/tr_TR.json
  i18n/locale/zh_CN.json
  i18n/locale/zh_HK.json
  i18n/locale/zh_SG.json
  i18n/locale/zh_TW.json
  tools/rvc_for_realtime.py
Labels: enhancement

#1719 Translation of RVC into Portuguese in i18n
  docs/pt-BR/Changelog_pt-BR.md
  docs/pt-BR/README.pt-BR.md
  docs/pt-BR/faiss_tips_BR.md
  docs/pt-BR/faq_pt-BR.md
  docs/pt-BR/training_tips_pt-BR.md
  i18n/locale/pt_BR.json
Labels: documentation

#1738 Added support for L4&RTX6000 GPU in WebUI
  infer-web.py
Labels: documentation, enhancement

#1775 Fix half argument (#1683)
  infer/modules/train/extract_feature_print.py
Labels: bug
